# Generated by Django 5.0.6 on 2025-03-17 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 1, 6, 43, 279124)),
        ),
    ]
