# Generated by Django 5.0.6 on 2025-03-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospital_jobtype_role_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
