# Generated by Django 5.0.6 on 2025-03-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_delete_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='bed_count',
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
    ]
