# Generated by Django 5.0.6 on 2025-03-22 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_department_bed_count_department_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
