# Generated by Django 5.0.6 on 2025-03-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_department_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
    ]
