# Generated by Django 5.0.6 on 2025-03-22 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_department_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
