# Generated by Django 5.0.6 on 2025-03-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_department_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bed_count',
            field=models.IntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
