# Generated by Django 5.0.6 on 2025-03-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_department_bed_count_alter_department_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='bed_count',
        ),
    ]
