# Generated by Django 5.0.6 on 2025-03-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_remove_department_bed_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
