# Generated by Django 5.0.6 on 2025-03-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_rename_specialization_employee_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hospital',
            field=models.ForeignKey(default='h1', on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
