# Generated by Django 5.0.6 on 2025-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_remove_user_role_remove_employee_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hospital',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
