# Generated by Django 5.0.6 on 2025-03-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_employee_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
