# Generated by Django 5.0.6 on 2025-03-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'job__job_name__iexact': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.employee'),
        ),
    ]
