# Generated by Django 5.0.6 on 2025-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='user', max_length=255, unique=True),
        ),
    ]
